### ISSUE TITLE
How to configure a custom port?

### ISSUE THREAD

**Issue by dotlnk-id2** [kkebo/DNSecure#89]
The default port 853 has security risks. How can I configure a custom port? Thank you

**Comment by kkebo** [comment]
DNSecure can't support a custom port because Apple doesn't support it.

We use the [`NEDNSSettingsManager`](https://developer.apple.com/documentation/networkextension/nednssettingsmanager), and it only supports the standard ports defined by RFCs.

Please send a feedback to Apple.

https://feedbackassistant.apple.com/
